### ISSUE TITLE
Add comment form is not cleared when a new comment is created

### ISSUE THREAD

**Issue by Fibii** [Fibii/Quest#29]
### Expected Behavior
`AddCommentForm` textfield should be cleared when a new comment is submitted and created. 

### Current Behavior
When a user adds a new comment, that is by typing a valid content in the comment `textfield` and presses the submit button, a new comment is added, and the comment content stays written in the comment `textfield`

### Possible Solution
pass [setCommentContent('')](https://github.com/Fibii/Quest/blob/8030e484c1202ef0a5c2f624c70faa7c2b73103e/frontend/src/components/Question/AddCommentForm.js#L45) as an argument to `dispatch()`, like this: `dispatch(setCommentContent(''))`

### Steps to Reproduce
1. login to the platform
2. create a question
3. add a comment to that question

**Comment by Jeanstaquet** [comment]
Hello, I think I can solve this mistake, I can work on it quickly.
